#######################################################################################
# Book settings
title                       : ""
author                      : Chung Chan  # The author of the book
copyright                   : "2021"      # Copyright year to be placed in the footer
logo                        : logo.dio.svg  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ref.bib

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true  # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'


#######################################################################################
# Parse and render settings
parse:
  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links
  myst_enable_extensions    :    
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
  myst_dmath_allow_labels   : true
  myst_dmath_double_inline  : true  # To allow display math (i.e. $$) within an inline context

#######################################################################################
# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : true
    utterances              : false

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : xelatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  
#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  jupyterhub_url            : "https://cs5483.cs.cityu.edu.hk"  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  binderhub_url             : "https://mybinder.org" # https://mybinder.org #https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" #https://colab.research.google.com # The URL of Google Colab (https://colab.research.google.com)
  
# Information about where the book exists on the web
repository:
  url: "https://github.com/ccha23/cs5483jupyter"  # Online location of your book
  path_to_book: "docs"  # An optional path to your book, defaults to repo root
  branch: "main"  # An optional branch, defaults to `master`

#######################################################################################
# Advanced and power-user settings
sphinx:
  config                    : # key-value pairs to directly over-ride the Sphinx configuration
    # mathjax_path              : https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      loader:
        load: ['[tex]/action',
                '[tex]/ams',
                '[tex]/amscd',
                '[tex]/bbox',
                '[tex]/boldsymbol',
                '[tex]/braket',
                '[tex]/bussproofs',
                '[tex]/cancel',
                # '[tex]/cases',   # missing empheq.js
                '[tex]/centernot',
                '[tex]/color',
                '[tex]/colorv2',
                '[tex]/colortbl',
                # '[tex]/empheq',   # missing empheq.js
                '[tex]/enclose',
                '[tex]/extpfeil',
                '[tex]/gensymb',
                '[tex]/html',
                '[tex]/mathtools',
                '[tex]/mhchem',
                '[tex]/newcommand',
                '[tex]/noerrors',
                '[tex]/noundefined',
                '[tex]/physics',
                '[tex]/upgreek',
                '[tex]/unicode',
                '[tex]/verb',
                '[tex]/configmacros',
                '[tex]/tagformat',
                '[tex]/textcomp',
                '[tex]/textmacros',
                '[tex]/setoptions',
                '[tex]/physics'
              ]
      tex:
        macros:
          mc: ["\\mathcal{#1}", 1]
          rsfs: ["\\mathsc{#1}", 1]
          R: ["\\mathsf{#1}", 1]
          M: ["\\boldsymbol{#1}", 1]
          RM: ["\\R{\\M{#1}}", 1]
        packages: [
                'base',
                'action',
                'ams',
                'amscd',
                'bbox',
                'boldsymbol',
                'braket',
                'bussproofs',
                'cancel',
                'cases',
                'centernot',
                'color',
                'colortbl',
                # 'empheq',   # missing empheq.js
                'enclose',
                'extpfeil',
                'gensymb',
                'html',
                'mathtools',
                'mhchem',
                'newcommand',
                'noerrors',
                'noundefined',
                'upgreek',
                'unicode',
                'verb',
                'configmacros',
                'tagformat',
                'textcomp',
                'textmacros',
                'physics']
    bibtex_default_style: "unsrt"
#     latex_toplevel_sectioning : 'part'
  extra_extensions          :   # A list of extra extensions to load by Sphinx (added to those already used by JB).
    - sphinx_proof
  local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
